name: ci

on:
  push:
    branches:
      - main
      - beta-pre-release
  pull_request:
    branches:
      - main
      - beta-pre-release

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm compile
      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v3
